game/urls.py
from django.urls import path

from . import views

app_name = 'game'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:game_id>', views.game, name='game'),
    path('creategame', views.create_game, name='create-game'),
    path('joingame', views.join_game, name='join-game'),
    path('spotifyauthorize', views.authorize, name='spotify-authorize'),
]

songle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls', namespace='game')),
    path('', RedirectView.as_view(url='game/', permanent=True)),
]

game/models.py
from django.db import models

# Create your models here.

game/views.py
import os
import base64

from django.http import HttpResponseRedirect, JsonResponse
import requests

from django.shortcuts import render


SONGLE_REDIRECT_URI = 'https://songle.up.railway.app/game/spotifyauthorize'


def index(request, user_data=None):
    return render(request, "game/index.html", user_data)


def game(request, game_id, playlist=None):
    # Render the game template.
    return render(request, "game/game.html", {
        'game_id': game_id,
        'username': request.GET['username'],
        'user_id': request.GET['user_id'],
        'playlist': playlist,
        'access_token': request.GET['access_token'],
        'refresh_token': request.GET['refresh_token'],
    })


def create_game(request):
    return game(request, request.GET['user_id'], request.GET['playlist'])


def join_game(request):
    return game(request, request.GET['game_id'])


def authorize(request):

    if 'code' in request.GET:
        # Load client id and secret
        client_id = os.environ['SONGLE_CLIENT_ID']
        client_secret = os.environ['SONGLE_CLIENT_SECRET']
        # Get base64 encoded client ID and secret
        authorization = f"{client_id}:{client_secret}"        
        authorization = authorization.encode('ascii')
        authorization = base64.b64encode(authorization)
        authorization = authorization.decode('ascii')

        # If a code is present, exchange the code for an access token
        response = requests.post(
            url = 'https://accounts.spotify.com/api/token',
            headers = {
                'Authorization': f'Basic {authorization}',
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            data={
                'grant_type': 'authorization_code',
                'code': request.GET['code'],
                'redirect_uri': SONGLE_REDIRECT_URI,
            }
        )
        response = response.json()

        # Save access and refresh tokens
        access_token = response['access_token']
        refresh_token = response['refresh_token']

        # Query user data
        response = requests.get(
            url = 'https://api.spotify.com/v1/me',
            headers = {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {response["access_token"]}',
            }
        )
        response = response.json()

        # Gather user data
        user_data = {
            'username': response['display_name'],
            'user_id': response['id'],
            'access_token': access_token,
            'refresh_token': refresh_token,
        }

        # Return to the index view
        return index(request, user_data)


    else:
        # If no code is present, request a code
        request = requests.Request(
            method='GET', 
            url='https://accounts.spotify.com/authorize', 
            params={
                'client_id': os.environ['SONGLE_CLIENT_ID'],
                'response_type': 'code',
                'redirect_uri': SONGLE_REDIRECT_URI,
            }).prepare()
        return HttpResponseRedirect(request.url)

game/templates/game/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'game/styles.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'game/favicon.ico' %}">
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body class="flex-column">
        <main class="flex-fill flex-even-space">
            {% block main %}{% endblock %}
        </main>
        <footer>&copy {% now "Y" %} Ifeanyi Obinelo</footer>
        {% block script %}{% endblock %}
    </body>
</html>

game/templates/game/game.html
{% extends "game/base.html" %}

{% load static %}

{% block title %}
    Game Room
{% endblock %}

{% block main %}

    <form hidden id="settings">
        <input type="hidden" value="{{ game_id }}" id="game-id">
        <input type="hidden" value="{{ playlist }}" id="playlist-id">
        <input type="hidden" value="{{ username }}" id="username">
        <input type="hidden" value="{{ user_id }}" id="user-id">
        <input type="hidden" value="{{ access_token }}" id="access-token">
        <input type="hidden" value="{{ refresh_token }}" id="refresh-token">
    </form>

    <div id="waiting-room" class="flex-column full-height">
        <div>
            <div class="game-subtitle">Copy join code</div>
            <div><button class="small-button" id="copy-code-button">Copy</button></div>
        </div>

        <div class="flex-fill">
            <div class="game-subtitle">Connected: <span id="number-of-connected-users"></span></div>
            <div id="connected-users"></div>
            <!--Add so that when a lotta people join, only top show. Or make it scroll.-->
        </div>

        <div>
            {% if user_id == game_id %}
                <button class="large-button" id="start-game-button">Start Game</button>
            {% else %}
                <button class="large-button" id="allow-autoplay-button">Allow Autoplay</button>
            {% endif %}
        </div>
    </div>

    <div id="playing-room" class="full-height flex-column no-display">
        <div id="tracks-container"></div>
        <div id="autocomplete-container">
            <ul id="autocomplete" class="unstyled"></ul>
        </div>
        <div id="search-container">
            <input id="track-search" placeholder="Type to search..." autocomplete="off" autofocus>
        </div>
    </div>

    <div id="scores-display" class="no-display">
        <div class="game-subtitle">Scores</div>
        <table id="scores-table">
            <tbody></tbody>
        </table>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'game/game.js' %}"></script>
{% endblock %}

game/templates/game/index.html
{% extends "game/base.html" %}

{% load static %}

{% block title %}
    Songle
{% endblock %}

{% block main %}
    <div>
        <div class="game-title">Songle</div>
        <div class="game-subtitle">Play with friends.</div>
    </div>

    <div>
        {% if not access_token %}
            <div class="game-subtitle">Log in to Spotify to start playing.</div class="game-subtitle">
            <a href="{% url 'game:spotify-authorize' %}">
                <button class="large-button">Log in to Spotify</button>
            </a>            
        {% else %}
            <div class="game-subtitle">Create a game</div>
            <form method="get" action="{% url 'game:create-game' %}">
                <input type="hidden" value="{{ username }}" name="username">
                <input type="hidden" value="{{ user_id }}" name="user_id">
                <input type="hidden" value="{{ access_token }}" name="access_token">
                <input type="hidden" value="{{ refresh_token }}" name="refresh_token">
                <div class="form-input">
                    <input type="text" name="playlist" placeholder="Enter playlist ID"><button type="submit" class="form-button">Create</button>
                </div>
            </form>
            <div class="game-subtitle">or</div>
            <div class="game-subtitle">Join a game</div>
            <form method="get" action="{% url 'game:join-game' %}">
                <input type="hidden" value="{{ username }}" name="username">
                <input type="hidden" value="{{ user_id }}" name="user_id">
                <input type="hidden" value="{{ access_token }}" name="access_token">
                <input type="hidden" value="{{ refresh_token }}" name="refresh_token">
                <div class="form-input">
                    <input type="text" name="game_id" placeholder="Enter game ID"><button type="submit" class="form-button">Join</button>
                </div>
            </form>
        {% endif %}
    </div>

    <div>
        <div class="game-subtitle">Powered by</div>
        <img src="{% static 'game/spotify/logos/spotify_logo_green.png' %}" alt="Spotify icon" class="spotify-icon-large">
    </div>
{% endblock %}